console.log(Math.round(4.7))
console.log(Math.pow(2,6))
console.log(Math.sqrt(9))
console.log(Math.min(1,5,3,0))
console.log(Math.max(1,5,3,0))
console.log(Math.floor(12.9))
console.log(Math.ceil(12.9))
